spring.application.name=gestion-stock

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestion_stock_db}
spring.datasource.username=${DB_USER:gestion_stock_user}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}